<script lang="ts">
    // In a real app, insights would be generated by some logic or AI in institutional-engine
    const insights = [
        {
            type: 'bullish',
            text: 'Foreign capital has been consistently net buying for 5 consecutive days, suggesting strong institutional accumulation.',
        },
        {
            type: 'bearish',
            text: 'Margin balance is approaching historical highs, which may increase market volatility in the short term.',
        },
        {
            type: 'neutral',
            text: 'Short-to-margin ratio remains low, indicating limited hedging activity among retail participants.',
        },
        {
            type: 'bullish',
            text: 'Domestic funds (Trust) have switched to net buying, providing potential support at current price levels.',
        },
    ];
</script>

<div
    class="insight-list-organism bg-surface-deep/40 rounded-3xl border border-white/[0.03] p-6 mb-8 backdrop-blur-xl relative overflow-hidden group shadow-2xl"
>
    <!-- Background Gradient -->
    <div
        class="absolute inset-0 bg-gradient-to-br from-accent/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none"
    ></div>

    <div class="relative z-10">
        <div class="flex items-center gap-3 mb-6">
            <span class="p-1.5 bg-accent/20 rounded-lg text-accent">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="w-4 h-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                </svg>
            </span>
            <div>
                <h3 class="text-sm font-black text-white/90 tracking-[0.2em] uppercase">
                    Intelligence_Insight
                </h3>
                <p class="text-[9px] font-mono text-white/20 mt-1 uppercase tracking-widest">
                    Aura_Nexus • Forensic_Synthesis
                </p>
            </div>
        </div>

        <div class="space-y-4">
            {#each insights as insight}
                <div
                    class="flex items-start gap-4 p-4 rounded-xl bg-black/20 border border-white/[0.02] hover:border-white/10 transition-all duration-300"
                >
                    <div
                        class="w-1.5 h-1.5 rounded-full mt-1.5 {insight.type === 'bullish'
                            ? 'bg-bullish'
                            : insight.type === 'bearish'
                              ? 'bg-bearish'
                              : 'bg-accent'} {insight.type !== 'neutral' ? 'animate-pulse' : ''}"
                    ></div>
                    <div class="flex-1">
                        <p class="text-[11px] font-mono leading-relaxed text-white/70">
                            {insight.text}
                        </p>
                        <div class="flex items-center gap-2 mt-2">
                            <span
                                class="text-[8px] font-mono font-black uppercase {insight.type ===
                                'bullish'
                                    ? 'text-bullish'
                                    : insight.type === 'bearish'
                                      ? 'text-bearish'
                                      : 'text-accent'} bg-white/5 px-1 py-0.5 rounded"
                            >
                                {insight.type}_SIGNAL
                            </span>
                        </div>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</div>
